#@data/values
---
system_domain: ""
system_namespace: ""

images:
  metric_proxy: "oratos/metric-proxy@sha256:fd2f5bad16596919d387c1374ee794e00329af7327f5aafd74d3e546e94180b0"

metric_proxy:
  enable_metrics_server: false
  ca:
    secret_name: "metric-proxy-ca"
    crt: "" #! Base64-encoded ca for the metric-proxy-ca
    key: "" #! Base64-encoded private key for the cert above
  cert:
    secret_name: "metric-proxy-cert"
    crt: "" #! Base64-encoded cert for the metric-proxy server requires CN of metric-proxy
    key: "" #! Base64-encoded private key for the cert above

